### ISSUE TITLE
Technically Constrain [C] for compliance with NS Rules

### ISSUE THREAD

**Issue by Redorhcs** [Krypton-Nova/Storm#2]
Putting this on the todo menu:

Constrain [C] with a debounce function to prevent execution more than once per minute. 

Example: https://stackoverflow.com/questions/24004791/can-someone-explain-the-debounce-function-in-javascript

I'll play around with it, been struggling as JS isn't my language :)

**Comment by bion33** [comment]
Solved in v1.6, commit f9959333839a24ce7db37a3b5421759c68eb2009

* [C] can't be used more than once a minute.
