### ISSUE TITLE
e.keyCode is deprecated

### ISSUE THREAD

**Issue by drehtisch** [Krypton-Nova/Storm#5]
![2021-01-18 17_26_35-Window](https://user-images.githubusercontent.com/38186302/104940711-0baafe00-59aa-11eb-959c-92b5980e29a2.png)

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

> You should avoid using this if possible; it's been deprecated for some time. Instead, you should use KeyboardEvent.code, if it's implemented. Unfortunately, some browsers still don't have it, so you'll have to be careful to make sure you use one which is supported on all target browsers.

**Comment by bion33** [comment]
I see an issue with the alternative "KeyboardEvent.key": the numpad number key values are the same as the top-row number key values, so I couldn't distinguish them.

Moreover, on an AZERTY layout the top-row number key values aren't numbers at all, but subject to the keyboard layout itself, meaning that it wouldn't be so easy to provide a default keyboard layout that works for everyone. 

This isn't even considering keyboards which don't follow the latin alphabet, which would be affected even worse... although those are probably not in use at all on NS.

**Comment by bion33** [comment]
So most likely, we'll have to use KeyboardEvent.code. But then there's the issue that the code does not necessarily represent the button on a non-US keyboard layout...
